### ISSUE TITLE
zp_picturefill not showing up under Plugins to activate in 1.4.9

### ISSUE THREAD

**Issue by JatB** [acrylian/zp_picturefill#9]
I installed zp_picturefill under the plugins folder but it is not showing up under the “Plugins” tab to activate. I have another optional plugin installed (the really handy preloadimage.php), so I know it works.

![zenphoto-plugins-all](https://cloud.githubusercontent.com/assets/10157440/9150160/2a7864d2-3d7f-11e5-8b44-4d4944a5d526.png)

I thought maybe it just needed to be in the plugins folder, so I modified my theme to use the new image calls, but all I got was pages with no images.

**Comment by acrylian** [comment]
Terribly sorry for the late reply but GitHub makes it really easy to miss new tickets not being listed on the overview lists…

You need to put the file and the folder of the same name into the `plugins` folder, not the whole folder you downloaded.

**Comment by JatB** [comment]
That did it. Thanks for the reply, our images now look great on our Retina screens and our standard screens.

You’ve always responded so fast on other bug posts that I was thinking about maybe replying on the regular forum, but I saw on your post about this plugin (http://www.zenphoto.org/support/topic.php?id=1007440) that you wanted us to post issues here.

I see from your link that it describes how to properly install plugins. It would be great on the Installation section of the README if it maybe clarified a little to prevent this issue (for people like me that might not find that page). Right now it says “Place the file and folder within your `/plugins` folder.” but the download includes multiple files and multiple folders.

So maybe something like-
You need to place only the ‘zp_picturefill.php’ and ‘zp_picturefill’ folder directly in the ‘/plugins’ folder, like so-

├── plugins
│   ├── zp_picturefill
│   │   └── picturefill.min.js
│   └── zp_picturefill.php


Thanks again for your time and hard work.

**Comment by acrylian** [comment]
Indeed, the instruction is wrong. Thanks, I will change that. It is a bit of a legacy that plugins are currently differently with single file plugins and file+folder ones.
